version: '3.9'

services:
  contact_postgres:
    image: postgres:16
    container_name: phonebook_contact_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: contactdb
    ports:
      - "5434:5432"
    volumes:
      - contact_pg_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql

  report_postgres:
    image: postgres:16
    container_name: phonebook_report_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: reportdb
    ports:
      - "5435:5432"
    volumes:
      - report_pg_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: phonebook_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5673:5672"
      - "15673:15672"

  contact-api:
    container_name: contact_api
    build:
      context: .
      dockerfile: src/Services/Contact/PhoneBookApp.Contact.API/Dockerfile
    depends_on:
      - contact_postgres
      - rabbitmq
    ports:
      - "5011:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker

  report-api:
    container_name: report_api
    build:
      context: .
      dockerfile: src/Report/PhoneBookApp.Report.API/Dockerfile
    depends_on:
      - report_postgres
      - rabbitmq
    ports:
      - "5012:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker

  gateway:
    container_name: api_gateway
    build:
      context: .
      dockerfile: src/PhoneBookApp.Gateway/Dockerfile
    depends_on:
      - contact-api
      - report-api
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker

volumes:
  contact_pg_data:
  report_pg_data:
